import 'dart:typed_data';
import 'package:excel/excel.dart';
import 'package:ftrace_web/features/products/model/product_model.dart';
import 'dart:convert';
import 'package:csv/csv.dart';

class ProductsExcelHelper {
  static List<ProductModel> parseExcel(
    Uint8List bytes,
    String hotelId,
    String hotelName,
  ) {
    var excel = Excel.decodeBytes(bytes);
    List<ProductModel> products = [];

    for (var table in excel.tables.keys) {
      var sheet = excel.tables[table]!;
      if (sheet.maxRows < 2) continue; // No data

      var headers = sheet.rows[0]
          .map((e) => e?.value?.toString().toLowerCase().trim() ?? '')
          .toList();

      // Find column indices
      int nameIdx = headers.indexOf('product name');
      if (nameIdx == -1) nameIdx = headers.indexOf('name');

      int uomIdx = headers.indexOf('uom');
      int invUomIdx = headers.indexOf('inventory uom');
      int convIdx = headers.indexOf('conversion factor');
      int barcodeIdx = headers.indexOf('barcode');
      int descIdx = headers.indexOf('description');
      int supplierIdx = headers.indexOf('supplier');
      int categoryIdx = headers.indexOf('categories');
      int statusIdx = headers.indexOf('status');

      if (nameIdx == -1 || uomIdx == -1 || invUomIdx == -1) {
        throw Exception(
          'Required columns missing: Product Name, UOM, Inventory UOM',
        );
      }

      for (int i = 1; i < sheet.maxRows; i++) {
        var row = sheet.rows[i];
        if (row.isEmpty) continue;

        String name = row[nameIdx]?.value?.toString().trim() ?? '';
        if (name.isEmpty) continue;

        products.add(
          ProductModel(
            id: '', // Will be generated by Firestore
            name: name,
            uom: row[uomIdx]?.value?.toString().trim() ?? '',
            inventoryUom: row[invUomIdx]?.value?.toString().trim() ?? '',
            conversionFactor:
                double.tryParse(row[convIdx]?.value?.toString() ?? '1') ?? 1.0,
            barcode: barcodeIdx != -1
                ? row[barcodeIdx]?.value?.toString().trim() ?? ''
                : '',
            description: descIdx != -1
                ? row[descIdx]?.value?.toString().trim() ?? ''
                : '',
            supplier: supplierIdx != -1
                ? row[supplierIdx]?.value?.toString().trim() ?? ''
                : '',
            categories: categoryIdx != -1
                ? (row[categoryIdx]?.value?.toString() ?? '')
                      .split(',')
                      .map((e) => e.trim())
                      .where((e) => e.isNotEmpty)
                      .toList()
                : [],
            status: statusIdx != -1
                ? row[statusIdx]?.value?.toString().toUpperCase().trim() ??
                      'ACTIVE'
                : 'ACTIVE',
            hotelId: hotelId,
            hotelName: hotelName,
          ),
        );
      }
    }
    return products;
  }

  static List<ProductModel> parseCsv(
    Uint8List bytes,
    String hotelId,
    String hotelName,
  ) {
    String csvString = utf8.decode(bytes);
    List<List<dynamic>> rows = const CsvToListConverter().convert(csvString);
    if (rows.length < 2) return [];

    var headers = rows[0]
        .map((e) => e.toString().toLowerCase().trim())
        .toList();

    int nameIdx = headers.indexOf('product name');
    if (nameIdx == -1) nameIdx = headers.indexOf('name');
    int uomIdx = headers.indexOf('uom');
    int invUomIdx = headers.indexOf('inventory uom');
    int convIdx = headers.indexOf('conversion factor');
    int barcodeIdx = headers.indexOf('barcode');
    int descIdx = headers.indexOf('description');
    int supplierIdx = headers.indexOf('supplier');
    int categoryIdx = headers.indexOf('categories');
    int statusIdx = headers.indexOf('status');

    if (nameIdx == -1 || uomIdx == -1 || invUomIdx == -1) {
      throw Exception(
        'Required columns missing: Product Name, UOM, Inventory UOM',
      );
    }

    List<ProductModel> products = [];
    for (int i = 1; i < rows.length; i++) {
      var row = rows[i];
      if (row.isEmpty) continue;

      String name = row[nameIdx]?.toString().trim() ?? '';
      if (name.isEmpty) continue;

      products.add(
        ProductModel(
          id: '',
          name: name,
          uom: row[uomIdx]?.toString().trim() ?? '',
          inventoryUom: row[invUomIdx]?.toString().trim() ?? '',
          conversionFactor:
              double.tryParse(row[convIdx]?.toString() ?? '1') ?? 1.0,
          barcode: barcodeIdx != -1
              ? row[barcodeIdx]?.toString().trim() ?? ''
              : '',
          description: descIdx != -1
              ? row[descIdx]?.toString().trim() ?? ''
              : '',
          supplier: supplierIdx != -1
              ? row[supplierIdx]?.toString().trim() ?? ''
              : '',
          categories: categoryIdx != -1
              ? (row[categoryIdx]?.toString() ?? '')
                    .split(',')
                    .map((e) => e.trim())
                    .where((e) => e.isNotEmpty)
                    .toList()
              : [],
          status: statusIdx != -1
              ? row[statusIdx]?.toString().toUpperCase().trim() ?? 'ACTIVE'
              : 'ACTIVE',
          hotelId: hotelId,
          hotelName: hotelName,
        ),
      );
    }
    return products;
  }

  static Uint8List? generateExcel(List<ProductModel> products) {
    var excel = Excel.createExcel();
    var sheet = excel['Products'];
    excel.setDefaultSheet('Products');

    // Headers
    sheet.appendRow([
      TextCellValue('Product Name'),
      TextCellValue('Barcode'),
      TextCellValue('Description'),
      TextCellValue('UOM'),
      TextCellValue('Inventory UOM'),
      TextCellValue('Conversion Factor'),
      TextCellValue('Supplier'),
      TextCellValue('Categories'),
      TextCellValue('Status'),
      TextCellValue('Hotel'),
    ]);

    for (var p in products) {
      sheet.appendRow([
        TextCellValue(p.name),
        TextCellValue(p.barcode),
        TextCellValue(p.description),
        TextCellValue(p.uom),
        TextCellValue(p.inventoryUom),
        DoubleCellValue(p.conversionFactor),
        TextCellValue(p.supplier),
        TextCellValue(p.categories.join(', ')),
        TextCellValue(p.status),
        TextCellValue(p.hotelName),
      ]);
    }

    return Uint8List.fromList(excel.encode()!);
  }
}
