// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQyeP-3JeQCqlB7i1_LciP_3eOu6vuscA',
    appId: '1:777712186190:web:3ae26ab77c6cf9b11ea41f',
    messagingSenderId: '777712186190',
    projectId: 'ftrace-a47c9',
    authDomain: 'ftrace-a47c9.firebaseapp.com',
    storageBucket: 'ftrace-a47c9.firebasestorage.app',
    measurementId: 'G-4N6C2MGXE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOP2OVWDStK52r4gVVIu0cGUzhgvxX3c8',
    appId: '1:777712186190:android:ef4dc0203133ce781ea41f',
    messagingSenderId: '777712186190',
    projectId: 'ftrace-a47c9',
    storageBucket: 'ftrace-a47c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSYr5PJSRY9BeI5VooPkAqz81qItEFFw8',
    appId: '1:777712186190:ios:e18e60452156e12c1ea41f',
    messagingSenderId: '777712186190',
    projectId: 'ftrace-a47c9',
    storageBucket: 'ftrace-a47c9.firebasestorage.app',
    iosBundleId: 'com.ftrace.web.ftraceWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSYr5PJSRY9BeI5VooPkAqz81qItEFFw8',
    appId: '1:777712186190:ios:e18e60452156e12c1ea41f',
    messagingSenderId: '777712186190',
    projectId: 'ftrace-a47c9',
    storageBucket: 'ftrace-a47c9.firebasestorage.app',
    iosBundleId: 'com.ftrace.web.ftraceWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQyeP-3JeQCqlB7i1_LciP_3eOu6vuscA',
    appId: '1:777712186190:web:edd1011a5c3893351ea41f',
    messagingSenderId: '777712186190',
    projectId: 'ftrace-a47c9',
    authDomain: 'ftrace-a47c9.firebaseapp.com',
    storageBucket: 'ftrace-a47c9.firebasestorage.app',
    measurementId: 'G-BS71D7PFMM',
  );
}
